{% set name = "seabirdscientific" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seabirdscientific-{{ version }}.tar.gz
  sha256: 2eeebb79698e3748cb9283e9e1dfa3029dd16ee0f08e8f90ab9b1cf9d6e65930

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - gsw
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - scipy

test:
  imports:
    - seabirdscientific
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Sea-Bird Scientific Community Toolkit
  home: https://github.com/Sea-BirdScientific/seabirdscientific
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/Sea-BirdScientific/seabirdscientific/tree/main/documentation
  summary: 'This is the repository for the Sea-Bird Scientific (SBS) Community Toolkit'

extra:
  recipe-maintainers:
    - darynwhite
