{% set name = "seabirdscientific" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seabirdscientific-{{ version }}.tar.gz
  sha256: 8c69cf31fc3357dc61f11d05e7905d85730db26e43404d54303310cc86d2f4b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - gsw 
    - matplotlib-base 
    - numpy 
    - pandas 
    - plotly >=6.0.0
    - scipy 
    # - ruff 
    # - python-build 
    # - pytest-cov 
    # - pytest 
    # - notebook 
    # - nbformat 
    # - nbconvert 
    # - kaleido 

test:
  imports:
    - seabirdscientific
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Sea-BirdScientific/seabirdscientific
  license: MIT
  license_file: LICENSE
  summary: 'This is the repository for the Sea-Bird Scientific (SBS) Community Toolkit'
  doc_url: https://github.com/Sea-BirdScientific/seabirdscientific/tree/main/documentation
  dev_url: https://github.com/Sea-BirdScientific/seabirdscientific/

extra:
  recipe-maintainers:
    - darynwhite
