{% set name = "seabirdscientific" %}
{% set version = "2.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seabirdscientific-{{ version }}.tar.gz
  sha256: bf49a962a4f389492430567847b861df2877c51168dcfaace0bb52d207bd6957

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - gsw 
    - matplotlib-base 
    - numpy 
    - pandas 
    - plotly >=6.0.0
    - scipy 
    # - twine 
    # - python-build 
    # - pytest 
    # - pylint 
    # - pre-commit 
    # - notebook 
    # - nbformat 
    # - mypy 
    # - black 
    # - twine 
    # - python-build 
    # - pytest-cov 
    # - pytest 
    # - pylint 
    # - pre-commit 
    # - notebook 
    # - nbformat 
    # - mypy 
    # - black 
    # - twine 
    # - python-build 
    # - pytest-cov 
    # - pytest 
    # - pylint 
    # - pre-commit 
    # - notebook 
    # - nbformat 
    # - mypy 
    # - black 
    # - twine 
    # - python-build 
    # - pytest-cov 
    # - pytest 
    # - pylint 
    # - pre-commit 
    # - notebook 
    # - nbformat 
    # - mypy 
    # - black 
    # - python-build 
    # - pytest-cov 
    # - pytest 
    # - pylint 
    # - notebook 
    # - nbformat 
    # - black ==25.1.0

test:
  imports:
    - seabirdscientific
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Sea-BirdScientific/seabirdscientific
  license: MIT
  license_file: LICENSE
  summary: 'This is the repository for the Sea-Bird Scientific (SBS) Community Toolkit'
  doc_url: https://github.com/Sea-BirdScientific/seabirdscientific/tree/main/documentation
  dev_url: https://github.com/Sea-BirdScientific/seabirdscientific/

extra:
  recipe-maintainers:
    - darynwhite
